import pickle, json, math, sys, warnings
warnings.filterwarnings('ignore')
import numpy as np
U='/mnt/user-data/uploads/'
SRC={'quoted_adr':'/home/claude/adr_retrain/adr_model_noleak.pkl',
     'conversion':U+'files_kim_new_model/adr_no_outliers2/conversion_model.pkl',
     'pickup_ipw':U+'pickup/pickup_model.pkl',
     'fnb':U+'f&b/fnb_model.pkl'}
def flat(tree, feats):
    idx={f:i for i,f in enumerate(feats)}
    nodes=[]; order={}
    def walk(n):
        pos=len(nodes); order[n['nodeid']]=pos; nodes.append(None)
        if 'leaf' in n:
            nodes[pos]=[float(n['leaf'])]; return pos
        kids={c['nodeid']:c for c in n['children']}
        y=walk(kids[n['yes']]); no=walk(kids[n['no']])
        miss = y if n['missing']==n['yes'] else no
        nodes[pos]=[idx[n['split']], float(n['split_condition']), y, no, miss]
        return pos
    walk(tree); return nodes
out={}; checks={}
for name,p in SRC.items():
    o=pickle.load(open(p,'rb')); m=o['model']; feats=o['features']; b=m.get_booster()
    cfg=json.loads(b.save_config()); bs=float(str(cfg['learner']['learner_model_param']['base_score']).strip('[]'))
    clf = cfg['learner']['objective']['name']=='binary:logistic'
    base = math.log(bs/(1-bs)) if clf else bs
    trees=[flat(json.loads(t),feats) for t in b.get_dump(dump_format='json')]
    out[name]={'b':base,'link':'logistic' if clf else 'identity','target':o['target'],'f':feats,'t':trees,
               'metrics':{k:(round(v,4) if isinstance(v,float) else v) for k,v in o['metrics'].items() if isinstance(v,(int,float))},
               'trained_at':o.get('trained_at_utc')}
    # verify against xgboost on random + boundary inputs
    rng=np.random.default_rng(0); X=rng.normal(size=(300,len(feats)))*rng.uniform(0.5,200,size=len(feats))
    X[rng.random(X.shape)<0.05]=np.nan
    ref = m.predict_proba(X)[:,1] if clf else m.predict(X)
    def ev(row):
        s=base
        for t in trees:
            n=t[0]
            while len(n)>1:
                v=row[n[0]]
                nxt=n[4] if v!=v else (n[2] if np.float32(v)<np.float32(n[1]) else n[3])
                n=t[nxt]
            s+=n[0]
        return 1/(1+math.exp(-s)) if clf else s
    mine=np.array([ev(r) for r in X])
    checks[name]=float(np.max(np.abs(mine-ref)))
    print(name,len(trees),'trees',len(feats),'features','max|diff|=%.2e'%checks[name], 'b=%.4f'%base)

# ── Proposal-composition helpers (trained here, same JS format) ─────────────
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import xgboost as xgb
df=pd.read_csv(U+'files_kim_new_model/adr_no_outliers2/rfp_training_data_complete_v3_with_transient.csv',low_memory=False)
HB=['room_block','nights','attendees','num_meeting_rooms','total_meeting_hours','num_sessions','full_day_pct','num_fnb_types','has_meeting_space','has_fnb_requirements','has_dinner','has_reception','max_av_level','baseline_adr']
X=df[HB].astype(float).fillna(0)
for tgt,key in [('proposed_total_revenue','est_proposed_total_revenue'),('room_revenue_ratio','est_room_revenue_ratio'),('meeting_ratio','est_meeting_ratio')]:
    y=df[tgt]; Xtr,Xte,ytr,yte=train_test_split(X,y,test_size=.25,random_state=1)
    m=xgb.XGBRegressor(n_estimators=200,max_depth=4,learning_rate=0.07,subsample=0.8,colsample_bytree=0.9,random_state=1,n_jobs=2).fit(Xtr,ytr)
    r2=float(r2_score(yte,m.predict(Xte)))
    m=xgb.XGBRegressor(n_estimators=200,max_depth=4,learning_rate=0.07,subsample=0.8,colsample_bytree=0.9,random_state=1,n_jobs=2).fit(X,y)
    b=m.get_booster(); cfg=json.loads(b.save_config()); bs=float(str(cfg['learner']['learner_model_param']['base_score']).strip('[]'))
    trees=[flat(json.loads(t),HB) for t in b.get_dump(dump_format='json')]
    out[key]={'b':bs,'link':'identity','target':tgt,'f':HB,'t':trees,'metrics':{'holdout_r2':round(r2,3)},'trained_at':'helper trained in this export from rfp_training_data_complete_v3_with_transient.csv'}
    rng=np.random.default_rng(1); Xr=X.sample(300,random_state=2).values; ref=m.predict(Xr); Xr=Xr.astype(np.float32).astype(np.float64)
    def ev2(row):
        s_=bs
        for t in trees:
            n=t[0]
            while len(n)>1:
                v=row[n[0]]; n=t[n[4] if v!=v else (n[2] if np.float32(v)<np.float32(n[1]) else n[3])]
            s_+=n[0]
        return s_
    print(key,'holdout R2 %.3f'%r2,'parity max diff %.2e'%max(abs(ev2(r)-p) for r,p in zip(Xr,ref)))

hdr='''// xgboost_trees_data_v8.js
// Auto-generated by convert.py from the newest Kim/Leila models (Sept 2026):
//   quoted_adr  <- RETRAINED without price-derived inputs (15 calendar/market features, test R2 0.908, MAE $6.32); the original 13-feature model leaked the quoted rate
//   conversion  <- adr_no_outliers2/conversion_model.pkl    (20 features, test accuracy 0.959)
//   pickup_ipw  <- pickup/pickup_model.pkl                  (10 features, R2 0.827, MAE 0.043)
//   fnb         <- f&b/fnb_model.pkl                        (10 features, R2 0.965, MAE $4.68)
//   est_*       three small helper models (proposed revenue, room share, meeting share of the proposal)
//               predicted from RFP-known fields, because three inputs of the conversion model are
//               shares of the hotel's own proposal; hold-out R2 0.93 / 0.95 / 0.62
// Format: { b: margin base score (logit for the classifier), link, f: feature names,
//           t: trees }. A node is [featureIndex, threshold, yesIdx, noIdx, missingIdx]
//           (go to yesIdx when value < threshold) or [leafValue].
// b is the model's true fitted base_score read from the pickle, so no calibration
// correction is needed (unlike xgboost_trees_data_v7.js).
// Trained on simulated RFP data: the metrics describe the simulation, not the hotel.

export const XGBOOST_TREES_V8 = '''
open('xgboost_trees_data_v8.js','w').write(hdr+json.dumps(out,separators=(',',':'))+';\n')
json.dump(checks,open('checks.json','w'))
