// perturbationTerms.js — fitted perturbation layer: Δ* = Δ + Σ_k β_k · z_k, z_k = (x_k − mean_k) / sd_k.
// Generated by scripts/fit_perturbation_terms.py. Label: SIMULATED (fit on simulated 2023-25 won groups; refit on real actuals).
// Candidates = factors the ADR, pickup and conversion models rely on + a few hand-picked ones.
// A term is ACCEPTED only if it is not an outcome leak, does not double count the base equations, is stable, and shrinks held-out error in every year-fold.
export const PERTURBATION_META = {
 "label": "Simulated",
 "n": 1299,
 "trained": "2023-2025 won groups (simulated)",
 "candidatesFromImportances": [
  "Is_Compression_Date",
  "arrival_day_of_week",
  "arrival_day_of_year",
  "confident_expected_pickup",
  "decision_time_days",
  "destinations_considered",
  "displacement_ema_7d",
  "forecasted_occupancy",
  "full_day_pct",
  "historical_demand_this_month",
  "is_peak_season",
  "is_shoulder_season",
  "lead_time_days",
  "market_seg_Healthcare",
  "market_seg_Travel",
  "on_books_occupancy_pct",
  "organization_industry_enc",
  "response_due_days",
  "segment_avg_revenue_intensity",
  "tr_transient_adr",
  "tr_transient_occ_of_available",
  "tr_transient_rooms_turned_away"
 ],
 "nCandidates": 28,
 "nLeak": 6,
 "nRedundant": 3,
 "nAbsorbed": 10,
 "nDoubleCount": 13,
 "nFitted": 18,
 "heldOut": {
  "year": 2025,
  "mae_bias_only": 1124.9992206942122,
  "mae_ridge": 1136.985253120775
 },
 "foldGainMae": [
  -4.8,
  -48.0,
  -12.0
 ],
 "allCandidatesHeldOut": {
  "mae_bias_only": 1124.9992206942122,
  "mae_ridge": 1123.2946724878786,
  "foldGain": [
   -40.8,
   -44.4,
   1.7
  ]
 },
 "gatePassed": false,
 "meanResidual": -257,
 "sdResidual": 2527,
 "cpor": 50
};
export const PERTURBATION_CANDIDATES = [
 {
  "factor": "historical_demand_this_month",
  "label": "Typical demand this month",
  "sources": [
   "adr",
   "conversion"
  ],
  "betaPerSd": -7.7,
  "ci95": [
   -22.8,
   7.6
  ],
  "stableInSample": false,
  "r2Base": 0.54,
  "betaAlone": -42.7,
  "betaControlled": 219.8,
  "doubleCounts": false,
  "mean": 162.4042,
  "sd": 23.0827,
  "status": "not used: unstable"
 },
 {
  "factor": "is_shoulder_season",
  "label": "Shoulder-season arrival",
  "sources": [
   "adr",
   "manual"
  ],
  "betaPerSd": -24.0,
  "ci95": [
   -57.0,
   3.7
  ],
  "stableInSample": false,
  "r2Base": 0.4,
  "betaAlone": -122.6,
  "betaControlled": 206.7,
  "doubleCounts": true,
  "mean": 0.4503,
  "sd": 0.4977,
  "status": "absorbed"
 },
 {
  "factor": "Is_Compression_Date",
  "label": "Sold-out (compression) date",
  "sources": [
   "adr"
  ],
  "status": "excluded: leak",
  "reason": "realised sold-out flag for the stay date"
 },
 {
  "factor": "displacement_ema_7d",
  "label": "Recent displacement trend",
  "sources": [
   "adr"
  ],
  "status": "excluded: leak",
  "reason": "moving average of realised displacement"
 },
 {
  "factor": "arrival_day_of_week",
  "label": "Arrival day of week",
  "sources": [
   "adr"
  ],
  "betaPerSd": -37.0,
  "ci95": [
   -64.8,
   -9.7
  ],
  "stableInSample": true,
  "r2Base": 0.64,
  "betaAlone": -154.0,
  "betaControlled": 553.2,
  "doubleCounts": false,
  "mean": 2.9492,
  "sd": 1.9784,
  "status": "not used: fails held-out"
 },
 {
  "factor": "arrival_day_of_year",
  "label": "Arrival day of year",
  "sources": [
   "adr"
  ],
  "betaPerSd": 1.9,
  "ci95": [
   -20.8,
   26.9
  ],
  "stableInSample": false,
  "r2Base": 0.12,
  "betaAlone": 18.8,
  "betaControlled": 164.5,
  "doubleCounts": true,
  "mean": 187.0408,
  "sd": 97.8731,
  "status": "absorbed"
 },
 {
  "factor": "segment_avg_revenue_intensity",
  "label": "Segment avg revenue intensity",
  "sources": [
   "adr",
   "pickup"
  ],
  "status": "excluded: leak",
  "reason": "segment mean that includes the group's own outcome"
 },
 {
  "factor": "confident_expected_pickup",
  "label": "Segment expected pickup (confident)",
  "sources": [
   "pickup"
  ],
  "betaPerSd": -12.7,
  "ci95": [
   -27.0,
   2.2
  ],
  "stableInSample": false,
  "r2Base": 0.99,
  "betaAlone": -68.0,
  "betaControlled": 201.6,
  "doubleCounts": true,
  "mean": 0.8471,
  "sd": 0.1314,
  "status": "redundant"
 },
 {
  "factor": "decision_time_days",
  "label": "Decision time (days)",
  "sources": [
   "pickup"
  ],
  "betaPerSd": 6.3,
  "ci95": [
   -18.6,
   30.8
  ],
  "stableInSample": false,
  "r2Base": 0.57,
  "betaAlone": 40.8,
  "betaControlled": -30.8,
  "doubleCounts": true,
  "mean": 27.0885,
  "sd": 8.9563,
  "status": "absorbed"
 },
 {
  "factor": "response_due_days",
  "label": "Response due (days)",
  "sources": [
   "pickup"
  ],
  "betaPerSd": -7.1,
  "ci95": [
   -37.8,
   20.2
  ],
  "stableInSample": false,
  "r2Base": 0.3,
  "betaAlone": -23.3,
  "betaControlled": -78.8,
  "doubleCounts": true,
  "mean": 7.2194,
  "sd": 3.2239,
  "status": "absorbed"
 },
 {
  "factor": "full_day_pct",
  "label": "Full-day meeting share",
  "sources": [
   "pickup"
  ],
  "betaPerSd": -1.4,
  "ci95": [
   -29.2,
   29.3
  ],
  "stableInSample": false,
  "r2Base": 0.22,
  "betaAlone": -21.8,
  "betaControlled": 49.9,
  "doubleCounts": true,
  "mean": 46.9182,
  "sd": 47.489,
  "status": "absorbed"
 },
 {
  "factor": "on_books_occupancy_pct",
  "label": "Rooms already booked on stay nights",
  "sources": [
   "conversion"
  ],
  "status": "excluded: leak",
  "reason": "on-the-books count includes the group's own block"
 },
 {
  "factor": "tr_transient_rooms_turned_away",
  "label": "tr_transient_rooms_turned_away",
  "sources": [
   "conversion"
  ],
  "status": "excluded: leak",
  "reason": "realised calendar value for the stay date"
 },
 {
  "factor": "forecasted_occupancy",
  "label": "Forecast hotel occupancy",
  "sources": [
   "conversion"
  ],
  "betaPerSd": -47.0,
  "ci95": [
   -61.8,
   -31.9
  ],
  "stableInSample": true,
  "r2Base": 0.52,
  "betaAlone": -212.4,
  "betaControlled": -358.9,
  "doubleCounts": false,
  "mean": 95.186,
  "sd": 10.8094,
  "status": "not used: fails held-out"
 },
 {
  "factor": "tr_transient_occ_of_available",
  "label": "tr_transient_occ_of_available",
  "sources": [
   "conversion"
  ],
  "status": "excluded: leak",
  "reason": "realised calendar value for the stay date"
 },
 {
  "factor": "lead_time_days",
  "label": "Lead time (days)",
  "sources": [
   "conversion",
   "manual"
  ],
  "betaPerSd": 1.7,
  "ci95": [
   -27.4,
   34.0
  ],
  "stableInSample": false,
  "r2Base": 0.75,
  "betaAlone": 17.0,
  "betaControlled": 9.3,
  "doubleCounts": true,
  "mean": 167.5689,
  "sd": 94.7334,
  "status": "absorbed"
 },
 {
  "factor": "destinations_considered",
  "label": "Destinations considered",
  "sources": [
   "conversion"
  ],
  "betaPerSd": -2.1,
  "ci95": [
   -31.3,
   28.9
  ],
  "stableInSample": false,
  "r2Base": 0.0,
  "betaAlone": -9.5,
  "betaControlled": -33.8,
  "doubleCounts": true,
  "mean": 2.0901,
  "sd": 0.948,
  "status": "absorbed"
 },
 {
  "factor": "is_peak_season",
  "label": "Peak-season arrival",
  "sources": [
   "conversion",
   "manual"
  ],
  "betaPerSd": 8.3,
  "ci95": [
   -19.7,
   32.4
  ],
  "stableInSample": false,
  "r2Base": 0.33,
  "betaAlone": 27.3,
  "betaControlled": 183.2,
  "doubleCounts": false,
  "mean": 0.5766,
  "sd": 0.4943,
  "status": "not used: unstable"
 },
 {
  "factor": "nights",
  "label": "Number of nights",
  "sources": [
   "manual"
  ],
  "betaPerSd": -33.0,
  "ci95": [
   -67.6,
   -0.2
  ],
  "stableInSample": true,
  "r2Base": 1.0,
  "betaAlone": -156.0,
  "betaControlled": -173.5,
  "doubleCounts": true,
  "mean": 1.6713,
  "sd": 0.7451,
  "status": "redundant"
 },
 {
  "factor": "log_block",
  "label": "Room block size (log)",
  "sources": [
   "manual"
  ],
  "betaPerSd": -10.6,
  "ci95": [
   -38.8,
   15.9
  ],
  "stableInSample": false,
  "r2Base": 0.88,
  "betaAlone": -68.9,
  "betaControlled": -25.2,
  "doubleCounts": true,
  "mean": 3.7028,
  "sd": 0.5552,
  "status": "redundant"
 },
 {
  "factor": "pickup_momentum",
  "label": "Recent pickup momentum",
  "sources": [
   "manual"
  ],
  "betaPerSd": 1.1,
  "ci95": [
   -40.3,
   38.8
  ],
  "stableInSample": false,
  "r2Base": 0.43,
  "betaAlone": -20.8,
  "betaControlled": 94.1,
  "doubleCounts": true,
  "mean": 0.8159,
  "sd": 0.0303,
  "status": "absorbed"
 },
 {
  "factor": "booking_pace_rooms_per_day",
  "label": "Booking pace (rooms/day)",
  "sources": [
   "manual"
  ],
  "betaPerSd": -4.0,
  "ci95": [
   -33.2,
   21.4
  ],
  "stableInSample": false,
  "r2Base": 0.13,
  "betaAlone": -28.4,
  "betaControlled": 30.1,
  "doubleCounts": true,
  "mean": 0.462,
  "sd": 0.9611,
  "status": "absorbed"
 },
 {
  "factor": "arrival_month_sin",
  "label": "Seasonal cycle (sin)",
  "sources": [
   "manual"
  ],
  "betaPerSd": -11.1,
  "ci95": [
   -38.4,
   11.1
  ],
  "stableInSample": false,
  "r2Base": 0.2,
  "betaAlone": -51.3,
  "betaControlled": -154.6,
  "doubleCounts": false,
  "mean": -0.0686,
  "sd": 0.7107,
  "status": "not used: unstable"
 },
 {
  "factor": "arrival_month_cos",
  "label": "Seasonal cycle (cos)",
  "sources": [
   "manual"
  ],
  "betaPerSd": -5.8,
  "ci95": [
   -25.8,
   18.6
  ],
  "stableInSample": false,
  "r2Base": 0.13,
  "betaAlone": -10.2,
  "betaControlled": -40.3,
  "doubleCounts": true,
  "mean": -0.0898,
  "sd": 0.6949,
  "status": "absorbed"
 },
 {
  "factor": "tr_transient_adr",
  "label": "tr_transient_adr",
  "sources": [
   "adr"
  ],
  "status": "excluded",
  "reason": "not in the training table"
 },
 {
  "factor": "market_seg_Travel",
  "label": "market_seg_Travel",
  "sources": [
   "pickup"
  ],
  "status": "excluded",
  "reason": "not in the training table"
 },
 {
  "factor": "organization_industry_enc",
  "label": "organization_industry_enc",
  "sources": [
   "pickup"
  ],
  "status": "excluded",
  "reason": "not in the training table"
 },
 {
  "factor": "market_seg_Healthcare",
  "label": "market_seg_Healthcare",
  "sources": [
   "pickup"
  ],
  "status": "excluded",
  "reason": "not in the training table"
 }
];
export const PERTURBATION_ACCEPTED = []; // empty = no term passed the held-out and double-counting checks, so Δ* = Δ

// x_k values known at quote time (null = not available here, term skipped)
export function perturbationFactors(rfp, nights) {
  const block = Number(rfp?.room_block) || 0;
  const v = { nights: nights || null, log_block: block > 0 ? Math.log1p(block) : null };
  if (rfp?.arrival_date && rfp?.inquiry_date) v.lead_time_days = Math.round((new Date(rfp.arrival_date) - new Date(rfp.inquiry_date)) / 864e5);
  return v;
}

// Returns { lines: [{label, factor, value}], total }
export function computePerturbation(factors) {
  const lines = [];
  for (const t of PERTURBATION_ACCEPTED) {
    const x = factors[t.factor];
    if (x == null || !isFinite(x)) continue;
    lines.push({ factor: t.factor, label: t.label, value: t.betaPerSd * (x - t.mean) / t.sd });
  }
  return { lines, total: lines.reduce((s, l) => s + l.value, 0) };
}
